apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/instance: test-resnet-jan24
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-resnet-jan24
  name: test-resnet-jan24
spec:
  port:
    targetPort: 8501
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: test-resnet-jan24
    weight: 100
  wildcardPolicy: None
