apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: test-resnet-jan24
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-resnet-jan24
  name: test-resnet-jan24
spec:
  ports:
    - port: 8501
      protocol: TCP
      targetPort: 8501
  selector:
    app.kubernetes.io/instance: test-resnet-jan24
